version: "3.8"

services:
  karaoke-web:
    build: .
    container_name: karaoke-web
    ports:
      - "8080:80"
    environment:
      ADMIN_PASSWORD: "supersecret"
    volumes:
      - .:/var/www/html
